version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
before_build:
- cmd: appveyor-retry nuget restore
build:
  verbosity: minimal
test:
  assemblies:
    only:
    - '**\*.UnitTest.dll'
artifacts:
- path: '**\*.nupkg'
  name: NuGet-Package
